version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "54320:5432"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080