FROM node:18-alpine AS builder

ENV NODE_ENV production
WORKDIR /ReactJS/social-network
COPY package.json .
COPY yarn.lock .
RUN yarn install --production
COPY . .
RUN yarn build

FROM nginx:1.23.1-alpine
COPY --from=builder /ReactJS/social-network/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]