import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/page2.module.css'
import { FaPlus, FaMinus } from 'react-icons/fa';
import { FormEvent, useState } from 'react';

const {
    h1, 'page-content': page_content, name, rounds,
    'action-icon': action_icon, main, 'bordered-row': bordered_row,
    head, minus, plus, 'add-button': add_button, form, 'form-group': form_group
} = styles;

export default function Home() {
    const [creatingPlayer, setCreatingPlayer] = useState(false)

    function NewUserButton(){
        return(
            <div className={`${add_button}`}
            onClick={switchCreating}
            >
                Adicionar novo jogador
            </div>
        )
    }
    
    function NewUserForm(){
        return (
            <form className={`${form}`}
            onSubmit={handleSubmit}
            >
                <div className={`form-group`}>
                    {/* <label htmlFor="name" className={`form-label`}>Nome</label> */}
                    <input id="name" type="text" className={`form-control`} placeholder='nome...'/>
                </div>
                <div className={`form-group`}>
                    {/* <label htmlFor="rounds" className={`form-label`}>Vagas</label> */}
                    <input id="rounds" type="number" className={`form-control`} placeholder='0'/>
                </div>
                <button type="submit" className={`btn btn-primary`}>CRIAR</button>
            </form>
        )
    }

    function switchCreating(){
        setCreatingPlayer(prevState => !prevState)
    }

    function handleSubmit(event: FormEvent){
        event.preventDefault()

        switchCreating()
    }

  return (
    // <div>
    // <div className={styles["page-content"]}>
    <div className={page_content}>
      <Head>
        <title>Comp do LOL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/toplane.png" />

      </Head>
      {/* <h1 className={styles.h1}>CONTROLE DE VAGAS</h1> */}
      <h1 className={`${h1} text-center`}>CONTROLE DE VAGAS</h1>
      <main className={`container-fluid ${main}`}>
        <div id="add-form" className={`row d-flex justify-content-center`}>
            <div className={`col-5 d-flex justify-content-center`}>
                {creatingPlayer? NewUserForm() : NewUserButton()}
            </div>
        </div>
        <div className={`row`}>
            <div className={`col-12`}>
                <div id="players-grid" className={`container-sm`}>
                    <div className={`row head ${head} ${bordered_row}`}>
                        <div className={`col-8 ${name} name`}>Nick</div>
                        <div className={`col-4 ${rounds} rounds`}>Vagas</div>
                    </div>
                    <div className={`row ${bordered_row}`}>
                        <div className={`col-8 ${name} name`}>Someone</div>
                        <div className={`col-2 ${rounds} rounds`}>10</div>
                        <div className={`col-1 ${action_icon} ${plus} action-icon`}>
                            <FaPlus />
                        </div>
                        <div className={`col-1 ${action_icon} ${minus} action-icon`}>
                            <FaMinus />
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </main>
    </div>
  )
}