version: '3.8'
services:
  react:
    container_name: react-development
    environment:
      - WATCHPACK_POLLING=true
    build:
      target: development
      context: ./frontend/
      dockerfile: Dockerfile.development
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
