# Generated by Django 2.2.13 on 2022-12-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='just a test description'),
            preserve_default=False,
        ),
    ]
