import { ReactNode } from 'react'
import Head from 'next/head'

export default function HEAD({ children }: { children: ReactNode }){
    return(
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />

            {children}
        </Head>
    )
}